Breaks DRAC configuration into stage1 and stage2
m-lab/epoxy-images pull request #192
Opened 2020-11-12 22:51 UTC by nkinkade

A new ePoxy extension was created to assist in creating GCD entities for BMCs on boot. The extension (bmc-store-password) URL is only available as a kernel parameter during the stage2 boot. Since stage2 is actually just a repurposed stage1 kernel and initramfs, this PR breaks DRAC configuration into two separate functions. One will be run during stage1 is is responsible for setting up the DRACs network configurations. Another will run during stage2 and is responsible for setting up login credentials for the BMC, and then storing those credentials in a GCD entity for the node.

2020-11-13 22:51 UTC, stephen-soltesz requested changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/192)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[configs/stage1_minimal/rc.local, line 81 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2iJaWD_OwF9V_qeki:-MM2iJaWD_OwF9V_qekj:b-q9bina) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L81)):*
> ```
>     local ipmi_ipv4
> 
>     load_ipmi_modules
> ```

nit: I recommend placing this operation (state changing) after the input checking of `$drac_ipv4` (not state changing) just below. If there's invalid input there's no need to change the system state / have side effects on return.
___
*[configs/stage1_minimal/rc.local, line 104 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2ikrL0tQ9RfSo3O-l:-MM2ikrL0tQ9RfSo3O-m:bwmi0u5) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L104)):*
> ```
>       echo $epoxy_ipv4 | tr ',' ' ' | (
>         read _ gateway _
>         logrun ipmitool user set name 2 "$BMC_STAGE1_USERNAME"
> ```

Ah! I see. The hint we can place about whether we've completed the password registration in stage2 is the username here.

Please add a comment explaining why we're resetting this username.
___
*[configs/stage1_minimal/rc.local, line 159 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2mzoh7d8BNtme-Kw6:-MM2mzoh7d8BNtme-Kw7:b-8nrrui) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L159)):*
> ```
>       logrun ipmitool user set password 2 "$password" 20
> 
>       if [[ -z bmc_store_password_url ]]; then
> ```

Please check for the URL before setting the password!
___
*[configs/stage1_minimal/rc.local, line 171 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2n5H-2-o_EUSfD1RT:-MM2n5H-2-o_EUSfD1RU:b2uyfdg) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L171)):*
> ```
>         # If the return code was not 200, attempt to set the BMC password back
>         # to known preset.
>         logrun ipmitool user set password 2 "$BMC_DEFAULT_PASSWORD" 20
> ```

And reset the username? That's how we decide to enter this block.
___
*[configs/stage1_minimal/rc.local, line 176 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2nCm23XquexM4Tip4:-MM2nCm23XquexM4Tip5:b-hu8k5t) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L176)):*
> ```
>       fi
>     else
>       echo "DRAC default user is already named $BMC_DEFAULT_USERNAME. Doing nothing..."
> ```

I'd encourage you to check this condition earlier, and return if nothing is needed.

Then the following logic doesn't have to be in an if block at all. I think this would make the logic a littler easier to follow.
___
*[configs/stage1_minimal/rc.local, line 186 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2hS5jASN1x8IHYR3x:-MM2hS5jASN1x8IHYR3y:bcyu5ra) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L186)):*
> ```
> echo "Downloading next stage from ePoxy"
> if grep epoxy.stage1 /proc/cmdline > /dev/null ; then
>   echo "Checking if stage1 DRAC configuration is needed..."
> ```

This message looks like it belongs in the `setup_drac_stage1` function.
___
*[configs/stage1_minimal/rc.local, line 190 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2hYkV1wAr4YraeZTC:-MM2hYkV1wAr4YraeZTD:b-816h6l) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L190)):*
> ```
>   epoxy_client -action epoxy.stage1 -add-kargs
> elif grep epoxy.stage2 /proc/cmdline > /dev/null ; then
>   echo "Checking if stage2 DRAC configuration is needed..."
> ```

Same.


<!-- Sent from Reviewable.io -->

2020-11-16 17:36 UTC, nkinkade reviewed
@stephen-soltesz: I believe I have addressed your comments. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/192#-:-MMH7I8T3yXi2_NGXFEk:bcbpk2l)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[configs/stage1_minimal/rc.local, line 81 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2iJaWD_OwF9V_qeki:-MMH2FiP2QFYTlhMqgal:b-896fix) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L81)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: I recommend placing this operation (state changing) after the input checking of `$drac_ipv4` (not state changing) just below. If there's invalid input there's no need to change the system state / have side effects on return.
</blockquote></details>

Done.
___
*[configs/stage1_minimal/rc.local, line 104 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2ikrL0tQ9RfSo3O-l:-MMH2k-B201363TOnkNY:b-896fix) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L104)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Ah! I see. The hint we can place about whether we've completed the password registration in stage2 is the username here.

Please add a comment explaining why we're resetting this username.
</blockquote></details>

Done.
___
*[configs/stage1_minimal/rc.local, line 159 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2mzoh7d8BNtme-Kw6:-MMH328i2hefTQMqykMb:b-qu6n94) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L159)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please check for the URL before setting the password!
</blockquote></details>

Good point. Done.
___
*[configs/stage1_minimal/rc.local, line 171 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2n5H-2-o_EUSfD1RT:-MMH3fZyAaTfiAelEJxH:b-896fix) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L171)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

And reset the username? That's how we decide to enter this block.
</blockquote></details>

Done.
___
*[configs/stage1_minimal/rc.local, line 176 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2nCm23XquexM4Tip4:-MMH5IJK5leMS4ea0z4g:b-896fix) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L176)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'd encourage you to check this condition earlier, and return if nothing is needed.

Then the following logic doesn't have to be in an if block at all. I think this would make the logic a littler easier to follow.
</blockquote></details>

Done.
___
*[configs/stage1_minimal/rc.local, line 186 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2hS5jASN1x8IHYR3x:-MMH6pgEEqguKusAgcqP:b-896fix) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L186)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This message looks like it belongs in the `setup_drac_stage1` function.
</blockquote></details>

Done.
___
*[configs/stage1_minimal/rc.local, line 190 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2hYkV1wAr4YraeZTC:-MMH6qgW7w_QVPVnl6-7:buymdqe) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L190)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

I didn't move this one because the logic for determining whether to do stage2 configuration was moved here.


<!-- Sent from Reviewable.io -->

2020-11-16 20:32 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/192)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[configs/stage1_minimal/rc.local, line 190 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2hYkV1wAr4YraeZTC:-MMHkKRRDjhfpbdoemLy:b-qd3e59) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L190)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I didn't move this one because the logic for determining whether to do stage2 configuration was moved here.
</blockquote></details>

Something doesn't look right. When is `$ipmi_user` set? I think all of this wants to be in the `setup_drac_stage2` function.


<!-- Sent from Reviewable.io -->

2020-11-16 20:44 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/192)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[configs/stage1_minimal/rc.local, line 190 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MM2hYkV1wAr4YraeZTC:-MMHmZN2CwpFsJiBZsWG:borlaze) ([raw file](https://github.com/m-lab/epoxy-images/blob/e45354918b762cab64551d73b65724ba8a06a726/configs/stage1_minimal/rc.local#L190)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Something doesn't look right. When is `$ipmi_user` set? I think all of this wants to be in the `setup_drac_stage2` function.
</blockquote></details>

Sorry, and thank you... it was a careless mistake. Fixed, I believe.


<!-- Sent from Reviewable.io -->

2020-11-16 21:31 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - with a few remaining tweaks and clarifications.

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/192#-:-MMHxzo81nK9hKguaLLl:b-iik87u)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[configs/stage1_minimal/rc.local, line 148 at r2](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MMHxSxH67caJD5h3mgm:-MMHxSxH67caJD5h3mgn:b-8rgwgm) ([raw file](https://github.com/m-lab/epoxy-images/blob/624d10f4e4ae73b39c133652115b817c8968297a/configs/stage1_minimal/rc.local#L148)):*
> ```
>     # need to configure the user name and password.
>     echo "Checking if stage2 DRAC configuration is needed..."
>     if [[ $ipmi_user == $BMC_DEFAULT_USERNAME ]]; then
> ```

In this case "default username" has a different meaning than "default password".

Here we want to terminate on the default username. I think this would be a little clearer if this name were not "default". e.g. maybe "bmc_stage2_username" or "bmc_final_username" or "bmc_admin_username".
___
*[configs/stage1_minimal/rc.local, line 173 at r2](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MMHvzPaAM395xr-j85P:-MMHvzPaAM395xr-j85Q:bfkfzxi) ([raw file](https://github.com/m-lab/epoxy-images/blob/624d10f4e4ae73b39c133652115b817c8968297a/configs/stage1_minimal/rc.local#L173)):*
> ```
>     fi
> 
>     logrun ipmitool user set name 2 admin
> ```

nit: use `$BMC_DEFAULT_USERNAME` ? instead of `admin`?
___
*[configs/stage1_minimal/rc.local, line 182 at r2](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MMHwHKlC4eNGIa0ic7G:-MMHwHKlC4eNGIa0ic7H:b-4p9ng9) ([raw file](https://github.com/m-lab/epoxy-images/blob/624d10f4e4ae73b39c133652115b817c8968297a/configs/stage1_minimal/rc.local#L182)):*
> ```
>     if [[ $bmc_store_password_status != "200" ]]; then
>       # If the return code was not 200, attempt to set the BMC user/password
>       # back to known presets.
> ```

"back to known values so that the next boot can try again." (or maybe "default values", if the variable names are adjusted).


<!-- Sent from Reviewable.io -->

2020-11-16 21:52 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/192)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[configs/stage1_minimal/rc.local, line 148 at r2](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MMHxSxH67caJD5h3mgm:-MMI1S9f3gdzDpdkON2L:b-8dulwc) ([raw file](https://github.com/m-lab/epoxy-images/blob/624d10f4e4ae73b39c133652115b817c8968297a/configs/stage1_minimal/rc.local#L148)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

In this case "default username" has a different meaning than "default password".

Here we want to terminate on the default username. I think this would be a little clearer if this name were not "default". e.g. maybe "bmc_stage2_username" or "bmc_final_username" or "bmc_admin_username".
</blockquote></details>

This makes sense. I've modified the variables with these names:

```
BMC_STAGE1_USERNAME
BMC_STAGE1_PASSWORD
BMC_FINAL_USERNAME
```
___
*[configs/stage1_minimal/rc.local, line 173 at r2](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MMHvzPaAM395xr-j85P:-MMI1gGK8k7v7iK9Fe4L:b-k2rwtz) ([raw file](https://github.com/m-lab/epoxy-images/blob/624d10f4e4ae73b39c133652115b817c8968297a/configs/stage1_minimal/rc.local#L173)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: use `$BMC_DEFAULT_USERNAME` ? instead of `admin`?
</blockquote></details>

Good catch. Fixed.
___
*[configs/stage1_minimal/rc.local, line 182 at r2](https://reviewable.io/reviews/m-lab/epoxy-images/192#-MMHwHKlC4eNGIa0ic7G:-MMI1i8s6hddF7NioagT:b-ol4ax5) ([raw file](https://github.com/m-lab/epoxy-images/blob/624d10f4e4ae73b39c133652115b817c8968297a/configs/stage1_minimal/rc.local#L182)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

"back to known values so that the next boot can try again." (or maybe "default values", if the variable names are adjusted).
</blockquote></details>

I modified the comment to be clearer.


<!-- Sent from Reviewable.io -->

2020-11-16 22:20 UTC, merged