Validate that cluster k8s version matches configured k8s version in this repo
m-lab/epoxy-images pull request #201
Opened 2021-02-04 23:22 UTC by nkinkade

This PR is intended to resolve #161.

As mentioned in #161, it is important that a node never have k8s components of a version greater than the API cluster version. This is because of the way that kubeadm works, which attempts to located special ConfigMaps in the cluster to configure itself, and those ConfigMaps have the k8s version in the name. This PR attempts to enforce that the API cluster version matches the configured version in this repository before building stage3 images.

One caveat to this PR is that there are possibly cases where we would want to upgrade the API cluster, yet wait to upgrade nodes, and meanwhile want to build stage3 epoxy-images. On the other hand, we don't want skew between the API cluster and nodes for very long, and this change is one way to help enforce that.

2021-02-05 17:44 UTC, stephen-soltesz requested changes
Thank you for looking into how to resolve #161 -- this will be a valuable safeguard to have in our system. My other comments have a suggestion that may achieve the same result a little more safely.

> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/201#-:-MSnHY250x5IBOq1V4zn:b-r8nm21)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[cloudbuild.yaml, line 29 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/201#-MSnGIyREs7hHwZ9YOWt:-MSnGIyREs7hHwZ9YOWu:b-zb8a67) ([raw file](https://github.com/m-lab/epoxy-images/blob/c1ea00a1b25ec4350f97feb5b748745a0819fe20/cloudbuild.yaml#L29)):*
> ```YAML
>     'cp',
>     'gs://k8s-support-$PROJECT_ID/admin.conf',
>     '/workspace/admin.conf',
> ```

This feels a little like distributing a root password. Is there a way that k8s-support could export the version to a common location that this repo could read (or anyone else) to learn the current platform cluster version?
___
*[setup_stage3_ubuntu.sh, line 57 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/201#-MSnH8Xs0CoxzahwyFKE:-MSnH8Xs0CoxzahwyFKF:bslhprb) ([raw file](https://github.com/m-lab/epoxy-images/blob/c1ea00a1b25ec4350f97feb5b748745a0819fe20/setup_stage3_ubuntu.sh#L57)):*
> ```Shell
>   https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl
> chmod +x /usr/bin/kubectl
> CLUSTER_VERSION=$(kubectl --kubeconfig admin.conf version --short | grep -i server | awk '{print $3}')
> ```

Could the k8s-support repo be the one to use the admin credentials to run this command to extract the version and make it available to other readers like epoxy-images?

For example, would we want to repeat this pattern if another script needs to discover the current platform cluster version? I think the current approach does not isolate security of the platform cluster adequately.


<!-- Sent from Reviewable.io -->

2021-02-05 18:38 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/201)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[cloudbuild.yaml, line 29 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/201#-MSnGIyREs7hHwZ9YOWt:-MSnIyw_EgK5fYgn1rba:bgwffyc) ([raw file](https://github.com/m-lab/epoxy-images/blob/c1ea00a1b25ec4350f97feb5b748745a0819fe20/cloudbuild.yaml#L29)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This feels a little like distributing a root password. Is there a way that k8s-support could export the version to a common location that this repo could read (or anyone else) to learn the current platform cluster version?
</blockquote></details>

I wasn't too worried about this, since the Cloud Build environment is ephemeral. We download the credentials and then when the build is finished the container is, presumably, irrevocably evaporated. My thinking was that if someone were to compromise either the epoxy-images repo or Cloud Build that the larger concern wouldn't be the admin.conf file in the ephemeral build environment, but that fact that the build environment has mostly unfettered access to GCS for that project and could easily just download that file, or any other sensitive data we may store in GCS.  
___
*[setup_stage3_ubuntu.sh, line 57 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/201#-MSnH8Xs0CoxzahwyFKE:-MSnJj4J7QIjLHGI_yns:bykrbsb) ([raw file](https://github.com/m-lab/epoxy-images/blob/c1ea00a1b25ec4350f97feb5b748745a0819fe20/setup_stage3_ubuntu.sh#L57)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Could the k8s-support repo be the one to use the admin credentials to run this command to extract the version and make it available to other readers like epoxy-images?

For example, would we want to repeat this pattern if another script needs to discover the current platform cluster version? I think the current approach does not isolate security of the platform cluster adequately.
</blockquote></details>

One issue I see with this is that this could only feasibly be triggered on a merge or tag to the k8s-support repo, and what is configured in the repo does not necessarily reflect what is deployed at any given moment (since building the repo does not perform cluster upgrades). This could mean that there are windows in which the k8s version exported by the k8s-support build does not reflect what is happening in the running cluster.  A hypothetical example: we tag k8s-support and at that moment the cluster is running, say, v1.18.15. Some hours or a day later I manually upgrade the running API cluster to v1.19.4 . Then the next day I want to tag epoxy-images to bring nodes up to version v1.19.4, but the build fails because the most recently exported version from k8s-support is still v1.18.15.  It wouldn't be until the next merge/tag of k8s-support until the exported version actually matches what is running in the cluster.


<!-- Sent from Reviewable.io -->

2021-02-05 18:54 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/201)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[cloudbuild.yaml, line 29 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/201#-MSnGIyREs7hHwZ9YOWt:-MSnX2reCDGo6fxPNbz6:b4dhhhs) ([raw file](https://github.com/m-lab/epoxy-images/blob/c1ea00a1b25ec4350f97feb5b748745a0819fe20/cloudbuild.yaml#L29)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I wasn't too worried about this, since the Cloud Build environment is ephemeral. We download the credentials and then when the build is finished the container is, presumably, irrevocably evaporated. My thinking was that if someone were to compromise either the epoxy-images repo or Cloud Build that the larger concern wouldn't be the admin.conf file in the ephemeral build environment, but that fact that the build environment has mostly unfettered access to GCS for that project and could easily just download that file, or any other sensitive data we may store in GCS.  
</blockquote></details>

Is there a way to export lower privilege credentials? Something akin to "read-only" access to the cluster to read the current version? How does prometheus get this information?
___
*[setup_stage3_ubuntu.sh, line 57 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/201#-MSnH8Xs0CoxzahwyFKE:-MSnXAlECq_M0XrKE9CP:bazwyzc) ([raw file](https://github.com/m-lab/epoxy-images/blob/c1ea00a1b25ec4350f97feb5b748745a0819fe20/setup_stage3_ubuntu.sh#L57)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

One issue I see with this is that this could only feasibly be triggered on a merge or tag to the k8s-support repo, and what is configured in the repo does not necessarily reflect what is deployed at any given moment (since building the repo does not perform cluster upgrades). This could mean that there are windows in which the k8s version exported by the k8s-support build does not reflect what is happening in the running cluster.  A hypothetical example: we tag k8s-support and at that moment the cluster is running, say, v1.18.15. Some hours or a day later I manually upgrade the running API cluster to v1.19.4 . Then the next day I want to tag epoxy-images to bring nodes up to version v1.19.4, but the build fails because the most recently exported version from k8s-support is still v1.18.15.  It wouldn't be until the next merge/tag of k8s-support until the exported version actually matches what is running in the cluster.
</blockquote></details>

I agree that a "live-read" is important here.

My concerns are:

* what is the implied API that we're setting up for accessing information from the platform cluster?
* what privilege is necessary for the level of access needed?

I believe the current approach is too broad. Can it be narrowed?


<!-- Sent from Reviewable.io -->

2021-02-05 23:58 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/201)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[setup_stage3_ubuntu.sh, line 57 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/201#-MSnH8Xs0CoxzahwyFKE:-MSoYUbM05BLOG96bovG:b-5dcjbm) ([raw file](https://github.com/m-lab/epoxy-images/blob/c1ea00a1b25ec4350f97feb5b748745a0819fe20/setup_stage3_ubuntu.sh#L57)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I agree that a "live-read" is important here.

My concerns are:

* what is the implied API that we're setting up for accessing information from the platform cluster?
* what privilege is necessary for the level of access needed?

I believe the current approach is too broad. Can it be narrowed?
</blockquote></details>

Exploring this a bit more, it seems that some limited non-sensitive information is available to unauthenticated users:

```
$ kubectl describe clusterrole system:public-info-viewer
Name:         system:public-info-viewer
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate: true
PolicyRule:
  Resources  Non-Resource URLs  Resource Names  Verbs
  ---------  -----------------  --------------  -----
             [/healthz]         []              [get]
             [/livez]           []              [get]
             [/readyz]          []              [get]
             [/version/]        []              [get]
             [/version]         []              [get]

$ kubectl describe clusterrolebinding system:public-info-viewer
Name:         system:public-info-viewer
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate: true
Role:
  Kind:  ClusterRole
  Name:  system:public-info-viewer
Subjects:
  Kind   Name                    Namespace
  ----   ----                    ---------
  Group  system:authenticated    
  Group  system:unauthenticated
```

And sure enough I can do this from my local machine:

```
$ curl --insecure  https://api-platform-cluster.mlab-sandbox.measurementlab.net:6443/version
{
  "major": "1",
  "minor": "18",
  "gitVersion": "v1.18.15",
  "gitCommit": "73dd5c840662bb066a146d0871216333181f4b64",
  "gitTreeState": "clean",
  "buildDate": "2021-01-13T13:14:05Z",
  "goVersion": "go1.13.15",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

I've updated this PR to do this instead.


<!-- Sent from Reviewable.io -->

2021-02-08 16:07 UTC, stephen-soltesz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/201#-:-MT1OM5z3Kx2dDAgZGw_:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[setup_stage3_ubuntu.sh, line 57 at r1](https://reviewable.io/reviews/m-lab/epoxy-images/201#-MSnH8Xs0CoxzahwyFKE:-MT1NskF8Iqz5puOF7jm:bwuv9uq) ([raw file](https://github.com/m-lab/epoxy-images/blob/c1ea00a1b25ec4350f97feb5b748745a0819fe20/setup_stage3_ubuntu.sh#L57)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Exploring this a bit more, it seems that some limited non-sensitive information is available to unauthenticated users:

```
$ kubectl describe clusterrole system:public-info-viewer
Name:         system:public-info-viewer
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate: true
PolicyRule:
  Resources  Non-Resource URLs  Resource Names  Verbs
  ---------  -----------------  --------------  -----
             [/healthz]         []              [get]
             [/livez]           []              [get]
             [/readyz]          []              [get]
             [/version/]        []              [get]
             [/version]         []              [get]

$ kubectl describe clusterrolebinding system:public-info-viewer
Name:         system:public-info-viewer
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate: true
Role:
  Kind:  ClusterRole
  Name:  system:public-info-viewer
Subjects:
  Kind   Name                    Namespace
  ----   ----                    ---------
  Group  system:authenticated    
  Group  system:unauthenticated
```

And sure enough I can do this from my local machine:

```
$ curl --insecure  https://api-platform-cluster.mlab-sandbox.measurementlab.net:6443/version
{
  "major": "1",
  "minor": "18",
  "gitVersion": "v1.18.15",
  "gitCommit": "73dd5c840662bb066a146d0871216333181f4b64",
  "gitTreeState": "clean",
  "buildDate": "2021-01-13T13:14:05Z",
  "goVersion": "go1.13.15",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

I've updated this PR to do this instead.
</blockquote></details>

Nice!!


<!-- Sent from Reviewable.io -->

2021-02-08 17:00 UTC, merged

2021-02-08 21:14 UTC, nkinkade reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/epoxy-images/201)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[setup_stage3_ubuntu.sh, line 59 at r2](https://reviewable.io/reviews/m-lab/epoxy-images/201#-MT2S35z7Wnyds4FbDU9:-MT2TuNNDWvMWYuBUCdw:b-9f8j31) ([raw file](https://github.com/m-lab/epoxy-images/blob/e0811a58967d04aeeaca8b5defddc0eb6af26b32/setup_stage3_ubuntu.sh#L59)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

@nkinkade - My focus was too much on the privileges to the API. I missed an important point.

I was imagining that this check would happen before the GCS copy. We don't want to overwrite good images with new images that won't work.

Failing fast is a good thing, so checking earlier is good. But, this build script couldn't be run stand-alone now, by a third party or by ourselves targeting any different version. Will this work when we're upgrading the cluster?
</blockquote></details>

I believe this check does happen before any images are copied to GCS. This script gets run in CB step #1, and images are not copied to GCS until step #3.  I initially had these checks directly in the builder.sh file, but decided that since this was very specific to stage3 Ubuntu images that it would be more appropriate to put the check here.

Why can't this script be run stand-alone any longer?


<!-- Sent from Reviewable.io -->